/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    CateAddOrUpdateModal: typeof import('./src/components/category/CateAddOrUpdateModal.vue')['default']
    CateQuery: typeof import('./src/components/category/CateQuery.vue')['default']
    CateTable: typeof import('./src/components/category/CateTable.vue')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    PkgAddOrUpdateModal: typeof import('./src/components/pkg/PkgAddOrUpdateModal.vue')['default']
    PkgQuery: typeof import('./src/components/pkg/PkgQuery.vue')['default']
    PkgTable: typeof import('./src/components/pkg/PkgTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheInput: typeof import('./src/components/form/TheInput.vue')['default']
    TheNav: typeof import('./src/components/TheNav.vue')['default']
    TheNumber: typeof import('./src/components/form/TheNumber.vue')['default']
    TheSelect: typeof import('./src/components/form/TheSelect.vue')['default']
    TheTreeSelect: typeof import('./src/components/form/TheTreeSelect.vue')['default']
    TreeSelect: typeof import('primevue/treeselect')['default']
  }
}
