/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    InputText: typeof import('primevue/inputtext')['default']
    PkgQuery: typeof import('./src/components/PkgQuery.vue')['default']
    PkgTable: typeof import('./src/components/PkgTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheInput: typeof import('./src/components/form/TheInput.vue')['default']
    TheNav: typeof import('./src/components/TheNav.vue')['default']
  }
}
