[package]
name = "sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.80"
dotenv = "0.15.0"
sqlx = { version = "0.7.3", features = ["runtime-tokio-rustls", "sqlite"] }
structopt = "0.3.26"
tokio = { version = "1.36.0", features = ["rt", "macros"] }
